sudo: required
dist: trusty
language: c++
env: VERBOSE=1

addons:
  apt:
    packages:
      - build-essential
      # We need this for clang builds
      - clang-3.8
      - libc++-dev

before_install:
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8 -stdlib=libc++"; fi

os:
  - linux

compiler:
  - clang

